apiVersion: v2
name: healthchecks-kubernetes
description: Automatically monitor Kubernetes CronJobs with self-hosted Healthchecks
version: 0.1.1
appVersion: "0.1.1"
type: application
home: https://github.com/felixtriller/healthchecks-kubernetes
sources:
  - https://github.com/felixtriller/healthchecks-kubernetes
annotations:
  org.opencontainers.image.source: https://github.com/felixtriller/healthchecks-kubernetes
