apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "healthchecks.fullname" . }}
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.config.namespace }}Role{{ else }}ClusterRole{{ end }}
metadata:
  name: {{ include "healthchecks.fullname" . }}
  {{- if .Values.config.namespace }}
  namespace: {{ .Values.config.namespace | quote }}
  {{- end }}
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
rules:
  - apiGroups: [batch]
    resources: [cronjobs]
    verbs: [get, list, watch]
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [get, list, watch, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.config.namespace }}RoleBinding{{ else }}ClusterRoleBinding{{ end }}
metadata:
  name: {{ include "healthchecks.fullname" . }}
  {{- if .Values.config.namespace }}
  namespace: {{ .Values.config.namespace | quote }}
  {{- end }}
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.config.namespace }}Role{{ else }}ClusterRole{{ end }}
  name: {{ include "healthchecks.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "healthchecks.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "healthchecks.fullname" . }}-state
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: [configmaps]
    verbs: [create]
  - apiGroups: [""]
    resources: [configmaps]
    resourceNames: [{{ include "healthchecks.fullname" . | quote }}]
    verbs: [get]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [create]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    resourceNames: [{{ include "healthchecks.fullname" . | quote }}]
    verbs: [get, update]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "healthchecks.fullname" . }}-state
  labels:
    {{- include "healthchecks.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "healthchecks.fullname" . }}-state
subjects:
  - kind: ServiceAccount
    name: {{ include "healthchecks.fullname" . }}
    namespace: {{ .Release.Namespace }}
