#!/bin/sh
# Writes the license and NOTICE files of everything compiled into the Linux
# controller binary: the Go runtime and each dependency module. The image build
# runs it; `make licenses` writes a local copy to bin/THIRD_PARTY_LICENSES.
set -eu

modules() {
	for arch in amd64 arm64; do
		GOOS=linux GOARCH=$arch CGO_ENABLED=0 go list -deps \
			-f '{{with .Module}}{{if not .Main}}{{.Path}}@{{.Version}} {{.Dir}}{{end}}{{end}}' \
			./cmd/healthchecks-kubernetes
	done | sort -u
}

section() {
	printf '%s\n\n' "================================================================================"
	printf '%s\n\n' "$1"
	for file in $2; do
		printf -- '--- %s ---\n\n' "$(basename "$file")"
		cat "$file"
		printf '\n'
	done
}

printf '%s\n\n' "Third-party software included in the healthchecks-kubernetes binary."
printf '%s\n\n' "Generated by scripts/third-party-licenses.sh; do not edit."

# Some packaged toolchains, such as Homebrew's, keep LICENSE beside GOROOT.
goroot=$(go env GOROOT)
for go_license in "$goroot/LICENSE" "$goroot/../LICENSE" ""; do
	[ -f "$go_license" ] && break
done
if [ -z "$go_license" ]; then
	echo "no license file found for the Go toolchain" >&2
	exit 1
fi
section "Go standard library and runtime" "$go_license"

modules | while read -r module dir; do
	files=$(find "$dir" -maxdepth 1 -type f \( -iname 'licen[cs]e*' -o -iname 'copying*' -o -iname 'notice*' \) | sort)
	if [ -z "$files" ]; then
		echo "no license file found for $module" >&2
		exit 1
	fi
	section "$module" "$files"
done
